---
title: "Standard Deviation"
output: html_notebook
---
```{r message=FALSE, warning=FALSE, error=TRUE}
library(readr)
library(dplyr)
```

```{r error=TRUE}
load("project.Rda")
```

```{r error=TRUE}
# Change these variables to be the standard deviation of each dataset.
# Inspect Data
head(london_data)
nrow(london_data)
temp <- london_data$TemperatureC
temp
average_temp <- mean(temp)
average_temp

# Variance and SD for the year
temperature_var <- var(temp)
temperature_var

temperature_standard_deviation <- sd(temp)
temperature_standard_deviation

#Inspect once again
head(london_data)
tail(london_data)
# Get monthly temperature average
june <- london_data %>%
  filter(month == "06")
print(june)  

july <- london_data %>%
   filter(month == "07")
print(july)   

print(mean(june$TemperatureC))
print(mean(july$TemperatureC))

print(sd(june$TemperatureC))
print(sd(july$TemperatureC))
 
monthly_stats <-london_data%>%
  group_by(month) %>%
  summarize(mean = mean(TemperatureC),
  standard_deviation = sd(TemperatureC))
monthly_stats

```